server:
  port: 9002
spring:
  application:
    name: service-ribbon


eureka:
  client:
    service-url:
      defaultZone: http://47.102.194.98:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
